// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   */
  long getProductId();

  /**
   * <code>int64 rating = 2;</code>
   */
  long getRating();
}
