// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public interface RatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 rating = 1;</code>
   */
  long getRating();

  /**
   * <code>string responseMessage = 2;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
