// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public interface RatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   */
  long getProductId();
}
