// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public final class RatingServiceOuterClass {
  private RatingServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ratingService.proto\"3\n\016ProductRequest\022" +
      "\021\n\tproductId\030\001 \001(\003\022\016\n\006rating\030\002 \001(\003\"\"\n\rRa" +
      "tingRequest\022\021\n\tproductId\030\001 \001(\003\"9\n\016Rating" +
      "Response\022\016\n\006rating\030\001 \001(\003\022\027\n\017responseMess" +
      "age\030\002 \001(\t\"&\n\013ApiResponse\022\027\n\017responseMess" +
      "age\030\001 \001(\t2v\n\rRatingService\022.\n\013RateProduc" +
      "t\022\017.ProductRequest\032\014.ApiResponse\"\000\0225\n\020Ge" +
      "tProductRating\022\016.RatingRequest\032\017.RatingR" +
      "esponse\"\000B\024\n\020cse.project.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRequest_descriptor,
        new java.lang.String[] { "ProductId", "Rating", });
    internal_static_RatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RatingRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_RatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RatingResponse_descriptor,
        new java.lang.String[] { "Rating", "ResponseMessage", });
    internal_static_ApiResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ApiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApiResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
